<a href="https://colab.research.google.com/github/FTKV/python-data-science-hw/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
"""
Домашнє завдання

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

Створіть прихований репозиторій на Гітхаб, надайте доступ ментору і усі наступні ДЗ повинні вивантажуватись у даний репозиторії.

Дз повинно бути виконано у Jupyter Nootebook,(або Google Colab) і задеплоїне на Гітхаб у вигляді файлу Hw1.ipynb Усі ячейки коду повинні бути виконані без Errors
"""

'\nДомашнє завдання\nСтворіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.\n\nСтворіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.\n\nСтворіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.\n\nСтворіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.\n\nСтворіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.\n\nСтворіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.\n\nСтворіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.\n\nСтворіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та

In [5]:
import numpy as np

In [11]:
#1
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
#2
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
#3
a = np.random.randint(1, 10, (5, 5))
print(a)

[[6 7 5 5 3]
 [8 2 9 2 2]
 [7 4 5 8 9]
 [3 1 2 7 6]
 [9 3 3 5 7]]


In [20]:
#4
a = np.random.random((4, 4))
print(a)

[[0.44738993 0.89750433 0.817876   0.75166292]
 [0.00304736 0.36229351 0.06362239 0.06107425]
 [0.94492455 0.32756616 0.86298617 0.27512052]
 [0.29845244 0.21188058 0.94176167 0.47844995]]


In [23]:
#5
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[6 9 8 8 8]
[5 2 3 3 4]
[11 11 11 11 12]
[1 7 5 5 4]
[30 18 24 24 32]


In [24]:
#6
a = np.random.random(7)
b = np.random.random(7)
print(a)
print(b)
print(np.dot(a, b))

[0.63852617 0.10397248 0.54497373 0.25785583 0.20228981 0.7449594
 0.78227495]
[0.30438706 0.04118293 0.12724121 0.10035993 0.53218239 0.04407171
 0.48308138]
0.8122516768842065


In [26]:
#7
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))
print(a)
print(b)
print(np.dot(a, b))

[[3 3]
 [4 7]]
[[7 9 7]
 [9 9 5]]
[[48 54 36]
 [91 99 63]]


In [29]:
#8
a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.linalg.inv(a))

[[1 7 9]
 [6 7 2]
 [7 8 7]]
[[-0.19186047 -0.13372093  0.28488372]
 [ 0.1627907   0.3255814  -0.30232558]
 [ 0.00581395 -0.23837209  0.20348837]]


In [31]:
#9
a = np.random.random((4, 4))
print(a)
print(a.T)

[[0.29845356 0.29065721 0.0240448  0.8388662 ]
 [0.73149443 0.3371922  0.76479088 0.93655463]
 [0.53811569 0.2324575  0.56185433 0.40763963]
 [0.56649939 0.11166576 0.92093362 0.65072016]]
[[0.29845356 0.73149443 0.53811569 0.56649939]
 [0.29065721 0.3371922  0.2324575  0.11166576]
 [0.0240448  0.76479088 0.56185433 0.92093362]
 [0.8388662  0.93655463 0.40763963 0.65072016]]


In [32]:
#10
a = np.random.randint(1, 10, (3, 4))
b = np.random.randint(1, 10, 4)
print(a)
print(b)
print(np.dot(a, b))

[[1 2 6 9]
 [4 2 5 5]
 [2 3 7 7]]
[7 6 3 8]
[109  95 109]


In [33]:
#11
a = np.random.random((2, 3))
b = np.random.random(3)
print(a)
print(b)
print(np.dot(a, b))

[[0.17484162 0.3689401  0.07756472]
 [0.58123967 0.57421626 0.49010735]]
[0.42406358 0.54288483 0.05866123]
[0.27898599 0.58696617]


In [34]:
#12
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(a)
print(b)
print(a * b)

[[9 5]
 [4 2]]
[[9 1]
 [7 1]]
[[81  5]
 [28  2]]


In [35]:
#13
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(a)
print(b)
print(np.dot(a, b))

[[2 4]
 [8 1]]
[[3 2]
 [8 2]]
[[38 12]
 [32 18]]


In [39]:
#14
a = np.random.randint(1, 100, (5, 5))
print(a)
print(a.sum())

[[64 27 33 78 15]
 [36  3 64 99 27]
 [10 66 20 40 31]
 [94 44 81 18  5]
 [70 88 43 91  9]]
1156


In [38]:
#15
a = np.random.randint(1, 10, (4, 4))
b = np.random.randint(1, 10, (4, 4))
print(a)
print(b)
print(a - b)

[[1 7 4 7]
 [4 5 3 2]
 [6 4 5 9]
 [4 7 9 6]]
[[8 7 1 5]
 [4 2 7 3]
 [8 4 6 4]
 [7 5 8 8]]
[[-7  0  3  2]
 [ 0  3 -4 -1]
 [-2  0 -1  5]
 [-3  2  1 -2]]


In [41]:
#16
a = np.random.random((3, 3))
print(a)
print(a.sum(axis=1))

[[0.46735119 0.93337306 0.06004385]
 [0.87695939 0.49118099 0.53220185]
 [0.79785081 0.29521708 0.11487298]]
[1.4607681  1.90034222 1.20794088]


In [45]:
#17
a = np.random.randint(1, 100, (3, 4))
print(a)
print(a ** 2)

[[72 33  5 79]
 [76 68 93 11]
 [32  3  1 71]]
[[5184 1089   25 6241]
 [5776 4624 8649  121]
 [1024    9    1 5041]]


In [46]:
#18
a = np.random.randint(1, 50, 4)
print(a)
print(a ** 0.5)

[46 38  6 20]
[6.78232998 6.164414   2.44948974 4.47213595]
